# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SnakeStrike
subtitle: An program for high-speed multi-camera data collection and triangulation.
email: grady.jensen@brml.org
github_username:  gwjensen
baseurl: "/SnakeStrike" # the subpath of your site, e.g. /blog
url: "https://gwjensen.github.io" # the base hostname & protocol for your site
repository: gwjensen/SnakeStrike

exclude:
    - "*.sh"
    - vendor # For Travis-CI (see https://jekyllrb.com/docs/continuous-integration/)

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

theme: jekyll-theme-slate
